cluster:
  name: odyssey
  profile: lsf2
  cores: 31
  timeout: 10000
  delay: 60

dir:
  results: results
  doc: doc
  ref: ref
  data: data

log_dir: log

encode_file: data/Encode_CD14_CD20_CD34_SKMC_HESC.txt
cell_types:
  - cd14
  - cd34
  - cd20
  - skmc
  - h1hesc

ref: /n/scratch00/hsph/biodata/genomes/Hsapiens/hg19/bowtie/hg19
gtf: /n/home05/kirchner/hsph_scratch/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf

annotation:
  name: hg19
  file: /n/home05/kirchner/hsph_scratch/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf

program:
  fastqc: fastqc
  tophat: tophat
  bowtie: bowtie
  picard: /n/home05/kirchner/opt/lib/java/picard-tools-1.74

stage:
  fastqc:
    name: fastqc
    program: fastqc
    options:
      - [--noextract]

  cutadapt:
    program: cutadapt
    platform: [illumina, polya]
    options:
      - [--error-rate, 0.1]
      - [--minimum-length, 20]
      - [--quality-cutoff, 20]

  tophat:
    name: tophat
    program: tophat
    quality_format: solexa
    max_errors: 2

  htseq-count:
    name: htseq-count
    program: htseq-count
    options:
      - [--stranded=no]
      - [--type=exon]
      - [--idattr=gene_id]
      - [--mode=union]

  rseqc:
    name: rseqc

run:
  [fastqc, cutadapt, fastqc, tophat, rseqc, htseq-count]
