cluster:
  name: odyssey
  profile: lsf
  cores: 8
  timeout: 10000
  delay: 10

dir:
  results: results
  doc: doc
  ref: ref
  data: data

log_dir: log

encode_file: data/Encode_CD14_CD20_CD34_SKMC_HESC.txt
gtf: /n/hsphS10/hsphfs1/chb/projects/lieberman_mirna/ref/Homo_sapiens.GRCh37.68.gtf
ref: /n/scratch00/hsph/biodata/genomes/Hsapiens/hg19/bowtie/hg19

program:
  fastqc: fastqc
  tophat: tophat
  bowtie: bowtie

stage:
  fastqc:
    name: fastqc
    program: fastqc
    options:
      - [--noextract]

  cutadapt:
    program: cutadapt
    platform: [illumina, polya]
    options:
      - [--error-rate, 0.1]
      - [--minimum-length, 20]

  tophat:
    name: tophat
    program: tophat
    quality_format: illumina
    max_errors: 2

  htseq-count:
    name: htseq-count
    program: htseq-count
    options:
      - [--stranded=no]
      - [--type=exon]
      - [--idattr=gene_id]
      - [--mode=union]

run:
  [download_encode, fastqc, cutadapt, tophat, htseq-count]