infile: origdata/Pertel_shRNA_raw_counts.csv
out_base: deseq-gene/Pertel_shRNA_gene
id_name: accession
min_count: 500
fdr_thresh: 0.1
multifactor: false
drop_replicates: [2]
model:
  condition:
    - d.3
    - d.3
    - d.3
    - w.3
    - w.3
    - w.3
  type:
    - standard
    - suspect
    - standard
    - standard
    - suspect
    - standard
