---
distribution: ubuntu
base_install: /usr/local
bii_dirname: bioinvindex
bii_lucene_index: index
bii_data_dirname: bii_data
bii_data_url: biidata
bii_layout_template: harvard-template
galaxy_dirname: galaxy
galaxy_repo: https://bitbucket.org/hbc/galaxy-central-hbc
galaxy_dbname: scde_galaxy
galaxy_adminusers: youradmin@email.com,anotheradmin@email.com
galaxy_datalib: datalibrary
db_user: galaxy
db_pass: galaxym3
