experiments:
  - name: JS03-6
    lineage: Gr
    timepoint: 15wk
  - name: JS03-7
    lineage: Gr
    timepoint: 21wk
  - name: JS03-8
    lineage: Gr
    timepoint: 23wk
  - name: JS04-12
    lineage: Gr
    timepoint: 28wk
  - name: JS03-9
    lineage: Gr
    timepoint: 32wk
  - name: JS03-10
    lineage: Gr
    timepoint: 36wk
  - name: JS03-11
    lineage: Gr
    timepoint: 41wk
  - name: JS04-1
    lineage: B
    timepoint: 15wk
  - name: JS04-2
    lineage: T
    timepoint: 15wk
  - name: JS04-3
    lineage: B
    timepoint: 23wk
  - name: JS04-4
    lineage: T
    timepoint: 23wk
  - name: JS04-5
    lineage: B
    timepoint: 36wk
  - name: JS04-6
    lineage: T
    timepoint: 36wk
  - name: JS04-7
    lineage: B
    timepoint: 41wk
  - name: JS04-8
    lineage: T
    timepoint: 41wk
  - name: JS04-9
    lineage: Tn
    timepoint:
  - name: JS03-12
    lineage: Tn
    timepoint:

dir:
  orig: origdata
