---
input:
  - fastq: Sequences/s_6_sequence.txt
    old_style_barcodes: true
    format: ILMFQ
    barcodes:
      - [bc1_outer, ATCACGA]
      - [bc2_itermed, CGATGTA]
      - [bc3_inner, TTAGGCA]
      - [bc4_genomic, TGACCAA]

ref: Resources/Genomes/hxb2.fa
expected:
  - name: gag
    file: Resources/ExpectedPercents/GagExpected-100_NO_INSERT.txt
    offset:
      790-1167: -1
      1168-1176:
      1177-2301: -10
  - name: rt
    file: Resources/ExpectedPercents/RTExpected-100.txt
    offset: -10

algorithm:
  # current algorithm parameters
  barcode_mismatch: 1
  allowed_ns: 0
  kmer_correct:
  trim_three: 36
  realignment: gatk
  kmer_size: 13
  min_qual: 20
  detection_thresh: 0.05
  # processing details
  cores: 1
  platform: illumina
  java_memory: 12g
  
program:
  barcode: barcode_sort_trim.py
  bamsort: picard_sam_to_bam.py
  uniquify: fastq-brentbioplayground
  picard: /n/sw/picard-tools-1.44
  gatk: /n/home05/bchapman/mylocal/share/java/gatk

dir:
  tmp: tmp
  align: align
  vrn: variation
