---
input:
  - fastq: Sequences/s_6_sequence.txt
    old_style_barcodes: true
    format: ILMFQ
    barcodes:
      - [bc1_outer, ATCACGA]
      - [bc2_itermed, CGATGTA]
      - [bc3_inner, TTAGGCA]
      - [bc4_genomic, TGACCAA]

ref: Resources/Genomes/hxb2.fa
expected:
  - name: gag
    file: Resources/ExpectedPercents/GagExpected-100_NO_INSERT.txt
    offset:
      790-1167: -1
      1168-1176:
      1177-2301: -10
  - name: rt
    file: Resources/ExpectedPercents/RTExpected-100.txt
    offset: -10

algorithm:
  # current algorithm parameters
  barcode_mismatch: 1
  allowed_ns: 0
  #kmer_correct: shrec -c 5
  realignment: gatk
  #trim_three: 36
  kmer_size: 13
  qual_thresh: 20
  kmer_thresh: 0.0025
  align_score_thresh: 150
  #range_params: [align_score_thresh]
  #align_score_thresh: [100, 125, 145, 150, 155, 175, 200]
  #qual_thresh: [10, 20, 30]
  #kmer_thresh: [0.01, 0.0075, 0.005, 0.0025, 0.001]
  # processing details
  cores: 4
  platform: illumina
  java_memory: 12g

roc_plot:
  region: rt
  qual: 20
  small_thresh: 5.0
  file: plot/roc_bc2.pdf
  curves:
    - name: Base
      file: variation_stats/6_bc2_itermed_1.yaml
    - name: Shrec
      file: variation_stats/6_bc2_itermed_1-no_ns-shrec-fix.yaml
    - name: Trim
      file: variation_stats/6_bc2_itermed_1-trim.yaml
  
program:
  barcode: barcode_sort_trim.py
  bamsort: picard_sam_to_bam.py
  uniquify: fastq-brentbioplayground
  picard: /n/sw/picard-tools-1.44
  gatk: /n/home05/bchapman/mylocal/share/java/gatk

dir:
  tmp: tmp
  align: align
  vrn: variation
  stats: variation_stats
  plot: plot
