
analysis: curoverse_wx7k5-d1hrv-038e7d7d7touaqi
url: https://workbench.wx7k5.arvadosapi.com/collections/download/wx7k5-4zz18-mt2ky0bruj0v3w1/361v43hr4p9p68mjsjdmejuufp9vmmvchp7dfj0239iu56zjda/1_24385-12878-30-200_AH5G7WCCXX.realigned.bam.realigned.indel.vcf.merged.Somatic.hc_filtered_merged_somatics_filtered_merged_somatics_snpEff_dbSNP_Cosmicv72.vcf
baseline: ../original_hartwig/24385-12878-30-200R_24385-12878-30-200T_filtered_merged_somatics_snpEff_dbSNP_Cosmicv72-cleaned.vcf.gz
truth:
  calls: ../../giab_truthset/na12878-na24385-somatic-truth.vcf.gz
  regions: ../../giab_truthset/na12878-na24385-somatic-truth-regions.bed
code:
  giab: ~/hsph/projects/giab_somatic
ref:
  rtg: /cm/shared/apps/bcbio/20141204-devel/data/genomes/Hsapiens/GRCh37/rtg/GRCh37.sdf
