base_dir: /home/bradc/data/tanzi_ad
idmapping: gwas/NIMH_Patient.Rutgers.ID_Translation.txt
priority: gwas/AD-Master-v2.csv
out: config/tanzi-alz-p1.yaml
params:
  priority: 1
  max_samples: 31
inputs:
  - /mnt/lustre/stripe-4M/harvard-illumina/LP*
