base_dir: /home/bradc/data/tanzi_ad
idmapping: gwas/NIMH_Patient.Rutgers.ID_Translation.txt
priority: gwas/WGS_NIMH_family_Prioritization_01-14-13_Raj.csv
out: config/tanzi-alz-p1.yaml
inputs:
  - /mnt/lustre/stripe-4M/harvard-illumina/LP*
