base_dir: /home/bradc/data/tanzi_ad
idmapping: gwas/NIMH_Patient.Rutgers.ID_Translation.txt
priority: gwas/AD-Master-v2.csv
coverage: inputs/alz-priority-regions.bed
# -- Priorty 2 variants
out: tanzi-alz-p2.yaml
params:
  name: p2
  families: ['51137', '88xxxx']
# -- Priorty family selection
# out: config/tanzi-alz-p1.yaml
# params:
#   name: p1
#   priority: 1
#   max_samples: 65
inputs:
  - /mnt/lustre/stripe-4M/harvard-illumina/LP*
